language: python
sudo: false
python:
  - 3.5
env:
  matrix:
    - TOXENV="py26"
    - TOXENV="py27"
    - TOXENV="py32"
    - TOXENV="py33"
    - TOXENV="py34"
    - TOXENV="py35"
    - TOXENV="pypy"
    - TOXENV="pypy3"

install: pip install tox
script: tox -e $TOXENV
